CREATE TABLE `tuples` (`id` INTEGER PRIMARY KEY, `tuple` VARCHAR(7) NOT NULL);
CREATE TABLE `words` (`id` INTEGER PRIMARY KEY,`word` VARCHAR(100) NOT NULL);
CREATE TABLE `words_tuples` (`id` INTEGER PRIMARY KEY AUTOINCREMENT,`word_id` INTEGER,`tuple_id` INTEGER);
